version: "3.8"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - "./:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
